"""
oam_gkp/qfi.py
==============
Quantum Fisher information (QFI) and classical Fisher information (CFI)
utilities.

Paper Eqs. (2) and (3):
    QFI (pure state)  : F_Q = 4 Var(G)  = 4 (<G^2> - <G>^2)
    QFI (mixed state) : F_Q = 2 sum_{j!=k} (lam_j - lam_k)^2 /
                                             (lam_j + lam_k) |<psi_j|G|psi_k>|^2

For phase estimation the generator is G = n_hat (photon number operator).
For a state rho after the noise channel (mixed), we use the spectral
decomposition formula and also provide a finite-difference estimator.

Paper Eq. (12): CFI of homodyne with LO angle psi:
    F_C(phi; psi) = |d<x_psi>/dphi|^2 / Var(x_psi)
"""

import numpy as np
import tensorflow as tf


# ─── Photon number operator ───────────────────────────────────────────────────

def number_operator(cutoff: int) -> tf.Tensor:
    """Diagonal photon-number operator in Fock space.

    n_hat = diag(0, 1, 2, ..., cutoff-1)

    Returns: shape (cutoff, cutoff), dtype complex128.
    """
    diag = tf.cast(tf.range(cutoff), tf.complex128)
    return tf.linalg.diag(diag)


def number_sq_operator(cutoff: int) -> tf.Tensor:
    """n_hat^2 = diag(0, 1, 4, ..., (cutoff-1)^2)."""
    diag = tf.cast(tf.range(cutoff) ** 2, tf.complex128)
    return tf.linalg.diag(diag)


# ─── QFI for pure states  (Paper Eq. 2) ──────────────────────────────────────

def qfi_pure(ket: tf.Tensor) -> tf.Tensor:
    """QFI for a pure state ket and generator G = n_hat.

    F_Q = 4 * Var(n_hat) = 4 * (<n^2> - <n>^2)

    Args:
        ket : state vector, shape (cutoff,), complex128.

    Returns:
        qfi : scalar, real-valued.
    """
    cutoff = ket.shape[0]
    n  = tf.cast(tf.range(cutoff), tf.float64)
    n2 = tf.cast(tf.range(cutoff) ** 2, tf.float64)

    probs = tf.cast(tf.abs(ket) ** 2, tf.float64)  # |<n|psi>|^2

    exp_n  = tf.reduce_sum(probs * n)
    exp_n2 = tf.reduce_sum(probs * n2)

    return 4.0 * (exp_n2 - exp_n ** 2)


# ─── QFI for mixed states  (Paper Eq. 3) ─────────────────────────────────────

def qfi_mixed(rho: tf.Tensor) -> tf.Tensor:
    """QFI for a mixed state density matrix and generator G = n_hat.

    F_Q = 2 sum_{j,k: lam_j + lam_k > 0}
              (lam_j - lam_k)^2 / (lam_j + lam_k) * |<psi_j|n|psi_k>|^2

    This uses the full spectral decomposition and is correct for any mixed
    state arising from noise channels.

    Args:
        rho : density matrix, shape (cutoff, cutoff), complex128.

    Returns:
        qfi : scalar, real-valued float64.
    """
    rho = tf.cast(rho, tf.complex128)
    cutoff = rho.shape[0]

    # Spectral decomposition: rho = V diag(lam) V^dagger
    # tf.linalg.eigh returns (eigenvalues, eigenvectors) for Hermitian matrices
    lam, V = tf.linalg.eigh(rho)
    lam    = tf.cast(tf.math.real(lam), tf.float64)   # eigenvalues, real

    # n_hat matrix in the eigenbasis:  n_eig = V^dag n_hat V
    n_hat  = number_operator(cutoff)
    n_eig  = tf.linalg.matmul(
                 tf.linalg.adjoint(V),
                 tf.linalg.matmul(n_hat, V)
             )                                          # (cutoff, cutoff), complex128

    # |<psi_j|n|psi_k>|^2
    n_abs2 = tf.cast(tf.abs(n_eig) ** 2, tf.float64)  # (cutoff, cutoff)

    # Compute (lam_j - lam_k)^2 / (lam_j + lam_k) for all pairs
    lam_j  = tf.expand_dims(lam, axis=1)               # (cutoff, 1)
    lam_k  = tf.expand_dims(lam, axis=0)               # (1, cutoff)
    sum_jk = lam_j + lam_k                              # (cutoff, cutoff)
    dif_jk = lam_j - lam_k

    # Mask out pairs with negligible population to avoid 0/0
    mask = tf.cast(sum_jk > 1e-10, tf.float64)
    ratio = tf.where(
        sum_jk > 1e-10,
        dif_jk ** 2 / (sum_jk + 1e-30),
        tf.zeros_like(sum_jk)
    )

    qfi = 2.0 * tf.reduce_sum(ratio * n_abs2 * mask)
    return qfi


# ─── Finite-difference QFI estimator ─────────────────────────────────────────

def qfi_finite_diff(
    rho_fn,                     # callable: phi -> rho(phi), returns (cutoff, cutoff)
    phi0: float = 0.0,
    delta_phi: float = 1e-4,
) -> tf.Tensor:
    """Estimate QFI via the quantum fidelity second derivative.

    For a family rho(phi) generated by unitary U(phi) = exp(-i phi n_hat):
        F_Q(phi) = -2 d^2 F / d(phi)^2 |_{dphi=0}
    where F(dphi) = Tr[rho(phi) rho(phi + dphi)] for pure states,
    or the Uhlmann fidelity for mixed states.

    This estimator is used as a check against the analytic formulas above.

    Args:
        rho_fn    : function mapping phi to density matrix.
        phi0      : reference phase.
        delta_phi : finite-difference step.

    Returns:
        qfi_est : estimated QFI, scalar.
    """
    rho0 = rho_fn(phi0)
    rho1 = rho_fn(phi0 + delta_phi)
    rho2 = rho_fn(phi0 - delta_phi)

    # Hilbert-Schmidt inner product  Tr[A B]
    def hs(A, B):
        return tf.math.real(tf.linalg.trace(
            tf.linalg.matmul(A, B, adjoint_a=True)
        ))

    F1  = hs(rho0, rho1)
    F_1 = hs(rho0, rho2)
    F0  = hs(rho0, rho0)

    # Second derivative by central differences
    d2F = (F1 - 2.0 * F0 + F_1) / (delta_phi ** 2)
    return tf.cast(-2.0 * d2F, tf.float64)


# ─── Classical Fisher information  (Paper Eq. 12) ────────────────────────────

def cfi_homodyne(
    rho: tf.Tensor,
    phi: tf.Tensor,
    psi: tf.Tensor,
    delta_phi: float = 1e-4,
) -> tf.Tensor:
    """CFI of homodyne detection at LO angle psi for phase phi.

    For homodyne with LO angle psi, the outcome is
        x_psi = q cos(psi) + p sin(psi)

    The mean and variance are obtained from the first and second moments of
    the Wigner function projected onto the x_psi axis:

        <x_psi>   = Tr[rho X_psi]
        Var(x_psi) = Tr[rho X_psi^2] - <x_psi>^2

    where X_psi = q cos(psi) + p sin(psi).

    We build these using the Fock-space position and momentum operators.

    Args:
        rho  : density matrix after noise, shape (cutoff, cutoff), complex128.
        phi  : encoded phase (scalar).
        psi  : homodyne LO angle (trainable scalar).
        delta_phi : finite-difference step for d<x_psi>/dphi.

    Returns:
        cfi : scalar float64.
    """
    cutoff = rho.shape[0]
    n      = tf.cast(tf.range(cutoff), tf.float64)

    # Build X_psi = q cos(psi) + p sin(psi) in Fock space.
    # q = (a + a^dag) / sqrt(2),  p = i(a^dag - a) / sqrt(2)
    # a |n> = sqrt(n) |n-1>,  a^dag |n> = sqrt(n+1) |n+1>
    psi_f = tf.cast(psi, tf.complex128)

    sq = tf.sqrt(tf.cast(tf.range(1, cutoff), tf.complex128))    # sqrt(1..cutoff-1)
    # annihilation operator  a
    a = tf.linalg.diag(sq, k=-1)                                  # (cutoff, cutoff)
    adag = tf.linalg.adjoint(a)

    q_op = (a + adag) / tf.cast(tf.sqrt(2.0), tf.complex128)
    p_op = 1j * (adag - a) / tf.cast(tf.sqrt(2.0), tf.complex128)

    cos_psi = tf.cast(tf.cos(tf.cast(psi, tf.float64)), tf.complex128)
    sin_psi = tf.cast(tf.sin(tf.cast(psi, tf.float64)), tf.complex128)
    X_psi   = cos_psi * q_op + sin_psi * p_op                     # (cutoff, cutoff)
    X_psi2  = tf.linalg.matmul(X_psi, X_psi)

    def mean_x(rho_m):
        return tf.math.real(tf.linalg.trace(
            tf.linalg.matmul(rho_m, X_psi)
        ))

    def var_x(rho_m):
        ex  = mean_x(rho_m)
        ex2 = tf.math.real(tf.linalg.trace(
            tf.linalg.matmul(rho_m, X_psi2)
        ))
        return ex2 - ex ** 2 + 1e-12   # add small regulariser

    # Derivative d<x_psi>/dphi via finite differences
    # Note: phi is the phase imprinted by R(phi) = exp(-i phi n_hat)
    # Shifting phi rotates rho accordingly.
    # We rotate rho in Fock space: rho(phi+d) = U(d) rho U(d)^dag
    d  = tf.cast(delta_phi, tf.float64)
    n_diag = tf.cast(tf.range(cutoff), tf.complex128)
    phase_plus  = tf.linalg.diag(tf.exp( 1j * tf.cast(d, tf.complex128) * n_diag))
    phase_minus = tf.linalg.diag(tf.exp(-1j * tf.cast(d, tf.complex128) * n_diag))

    rho_plus  = tf.linalg.matmul(phase_plus,  tf.linalg.matmul(rho, tf.linalg.adjoint(phase_plus)))
    rho_minus = tf.linalg.matmul(phase_minus, tf.linalg.matmul(rho, tf.linalg.adjoint(phase_minus)))

    dmean_dphi = (mean_x(rho_plus) - mean_x(rho_minus)) / (2.0 * d)

    cfi = dmean_dphi ** 2 / var_x(rho)
    return tf.cast(cfi, tf.float64)


# ─── Measurement efficiency ───────────────────────────────────────────────────

def measurement_efficiency(cfi: tf.Tensor, qfi: tf.Tensor) -> tf.Tensor:
    """Ratio CFI / QFI; equals 1 iff measurement saturates QCRB."""
    return cfi / (qfi + 1e-12)


# ─── Normalised QFI (relative to Heisenberg limit) ───────────────────────────

def normalised_qfi(qfi: tf.Tensor, mean_n: tf.Tensor) -> tf.Tensor:
    """QFI / (4 n_bar^2) — fraction of Heisenberg limit achieved.

    Heisenberg limit for photon number generator: F_Q^{HL} = 4 n_bar^2.

    Returns a value in [0, 1] for states at or below the HL.
    """
    hl = 4.0 * tf.cast(mean_n, tf.float64) ** 2 + 1e-12
    return qfi / hl
